"""
grudarin.core.logger
Writes structured session notes in both Markdown and JSON formats.
All data is written locally. No network calls. No telemetry.
"""

import os
import json
import time
import threading
from datetime import datetime
from typing import Optional
from collections import defaultdict, deque

from core.topology import TopologyGraph


MARKDOWN_TEMPLATE = """# grudarin Session Report
**Generated by grudarin** - Network Intelligence Monitor  
**Session ID:** {session_id}  
**Interface:** {interface}  
**Started:** {start_time}  
**Ended:** {end_time}  
**Duration:** {duration}  

---

## Summary

| Metric | Value |
|---|---|
| Total Devices | {total_devices} |
| Total Links | {total_links} |
| Packets Captured | {total_packets} |
| Total Data | {total_bytes} |

---

## Discovered Devices

{devices_table}

---

## Network Links

{links_table}

---

## Protocol Distribution

{protocol_table}

---

## Event Timeline

{event_log}

---

## Raw Packet Statistics

{packet_stats}

---

*End of Report - grudarin*
"""


class SessionLogger:

    def __init__(self, output_dir: str, interface: str):
        self.output_dir = output_dir
        self.interface = interface
        self.session_id = datetime.now().strftime("%Y%m%d_%H%M%S")
        self.start_time = time.time()

        # Ensure session directory exists
        self.session_dir = os.path.join(output_dir, f"grudarin_{self.session_id}")
        os.makedirs(self.session_dir, exist_ok=True)

        # File paths
        self.events_path = os.path.join(self.session_dir, "events.jsonl")
        self.packets_path = os.path.join(self.session_dir, "packets.jsonl")
        self.report_md_path = os.path.join(self.session_dir, "report.md")
        self.report_json_path = os.path.join(self.session_dir, "report.json")

        # In-memory accumulators
        self._lock = threading.Lock()
        self._packet_count = 0
        self._byte_count = 0
        self._protocol_counts = defaultdict(int)
        self._event_log = []
        self._recent_packets = deque(maxlen=10000)

        # File handles
        self._events_fh = None
        self._packets_fh = None

    def start(self):
        self._events_fh = open(self.events_path, "a", encoding="utf-8")
        self._packets_fh = open(self.packets_path, "a", encoding="utf-8")
        self._log_event("session_start", {
            "session_id": self.session_id,
            "interface": self.interface,
            "start_time": self.start_time,
        })
        print(f"[grudarin] Session notes saving to: {self.session_dir}")

    def stop(self, topology: TopologyGraph):
        self._log_event("session_end", {
            "packets": self._packet_count,
            "bytes": self._byte_count,
            "devices": topology.device_count(),
            "links": topology.link_count(),
        })
        if self._events_fh:
            self._events_fh.close()
        if self._packets_fh:
            self._packets_fh.close()
        self._write_final_report(topology)

    def log_packet(self, event: dict):
        with self._lock:
            self._packet_count += 1
            self._byte_count += event.get("size", 0)
            proto = event.get("protocol", "unknown")
            self._protocol_counts[proto] += 1
            self._recent_packets.append(event)

        if self._packets_fh:
            try:
                self._packets_fh.write(json.dumps(event) + "\n")
                self._packets_fh.flush()
            except Exception:
                pass

    def log_topology_event(self, event_type: str, data: dict):
        self._log_event(event_type, data)

    def _log_event(self, event_type: str, data: dict):
        ts = time.time()
        entry = {
            "time": ts,
            "time_human": datetime.fromtimestamp(ts).isoformat(),
            "event": event_type,
            "data": data,
        }
        with self._lock:
            self._event_log.append(entry)
        if self._events_fh:
            try:
                self._events_fh.write(json.dumps(entry) + "\n")
                self._events_fh.flush()
            except Exception:
                pass

    def get_packet_count(self) -> int:
        return self._packet_count

    def get_byte_count(self) -> int:
        return self._byte_count

    def get_protocol_counts(self) -> dict:
        with self._lock:
            return dict(self._protocol_counts)

    def _write_final_report(self, topology: TopologyGraph):
        end_time = time.time()
        duration_sec = int(end_time - self.start_time)
        hours = duration_sec // 3600
        minutes = (duration_sec % 3600) // 60
        seconds = duration_sec % 60
        duration_str = f"{hours:02d}h {minutes:02d}m {seconds:02d}s"

        devices = topology.all_devices()
        links = topology.all_links()

        # ---- Build devices table ----
        dev_rows = []
        dev_rows.append("| MAC | IP | Hostname | Vendor | OS Guess | Type | Packets TX | Packets RX | Protocols |")
        dev_rows.append("|---|---|---|---|---|---|---|---|---|")
        for dev in sorted(devices, key=lambda d: d.ip or ""):
            protocols = ", ".join(sorted(dev.protocols_seen)) or "-"
            dev_rows.append(
                f"| {dev.mac} | {dev.ip or '-'} | {dev.hostname or '-'} "
                f"| {dev.vendor or '-'} | {dev.os_guess or '-'} "
                f"| {dev.node_type} | {dev.packets_sent} | {dev.packets_received} "
                f"| {protocols} |"
            )
        devices_table = "\n".join(dev_rows)

        # ---- Build links table ----
        link_rows = []
        link_rows.append("| Source MAC | Destination MAC | Protocol | Packets | Bytes |")
        link_rows.append("|---|---|---|---|---|")
        for link in sorted(links, key=lambda l: l.packet_count, reverse=True)[:200]:
            link_rows.append(
                f"| {link.src_mac} | {link.dst_mac} "
                f"| {link.protocol} | {link.packet_count} | {link.byte_count} |"
            )
        links_table = "\n".join(link_rows)

        # ---- Protocol table ----
        proto_rows = []
        proto_rows.append("| Protocol | Packet Count | Percentage |")
        proto_rows.append("|---|---|---|")
        total = self._packet_count or 1
        for proto, count in sorted(self._protocol_counts.items(), key=lambda x: x[1], reverse=True):
            pct = round(count / total * 100, 2)
            proto_rows.append(f"| {proto} | {count} | {pct}% |")
        protocol_table = "\n".join(proto_rows)

        # ---- Event log ----
        event_lines = []
        for entry in self._event_log:
            ts_human = entry.get("time_human", "")
            ev = entry.get("event", "")
            data = entry.get("data", {})
            summary = self._summarize_event(ev, data)
            event_lines.append(f"- `{ts_human}` **{ev}** - {summary}")
        event_log = "\n".join(event_lines) or "No events recorded."

        # ---- Packet stats ----
        packet_stats = (
            f"Total Packets: {self._packet_count}\n\n"
            f"Total Bytes: {self._format_bytes(self._byte_count)}\n\n"
            f"Average Packet Size: {round(self._byte_count / (self._packet_count or 1), 1)} bytes"
        )

        # ---- Render Markdown ----
        report_md = MARKDOWN_TEMPLATE.format(
            session_id=self.session_id,
            interface=self.interface,
            start_time=datetime.fromtimestamp(self.start_time).strftime("%Y-%m-%d %H:%M:%S"),
            end_time=datetime.fromtimestamp(end_time).strftime("%Y-%m-%d %H:%M:%S"),
            duration=duration_str,
            total_devices=len(devices),
            total_links=len(links),
            total_packets=self._packet_count,
            total_bytes=self._format_bytes(self._byte_count),
            devices_table=devices_table,
            links_table=links_table,
            protocol_table=protocol_table,
            event_log=event_log,
            packet_stats=packet_stats,
        )

        with open(self.report_md_path, "w", encoding="utf-8") as f:
            f.write(report_md)

        # ---- Render JSON ----
        report_json = {
            "session_id": self.session_id,
            "interface": self.interface,
            "start_time": self.start_time,
            "end_time": end_time,
            "duration_seconds": duration_sec,
            "stats": {
                "total_devices": len(devices),
                "total_links": len(links),
                "total_packets": self._packet_count,
                "total_bytes": self._byte_count,
                "protocols": dict(self._protocol_counts),
            },
            "devices": [d.to_dict() for d in devices],
            "links": [l.to_dict() for l in links],
            "events": self._event_log,
        }
        with open(self.report_json_path, "w", encoding="utf-8") as f:
            json.dump(report_json, f, indent=2, default=str)

        print(f"[grudarin] Report saved:")
        print(f"           Markdown : {self.report_md_path}")
        print(f"           JSON     : {self.report_json_path}")

    def _summarize_event(self, event_type: str, data: dict) -> str:
        if event_type == "device_added":
            mac = data.get("mac", "?")
            ip = data.get("ip", "?")
            vendor = data.get("vendor", "?")
            return f"New device: {mac} / {ip} / {vendor}"
        if event_type == "link_added":
            return f"{data.get('src_mac', '?')} -> {data.get('dst_mac', '?')} via {data.get('protocol', '?')}"
        if event_type == "session_start":
            return f"Monitoring started on {data.get('interface', '?')}"
        if event_type == "session_end":
            return f"Captured {data.get('packets', 0)} packets from {data.get('devices', 0)} devices"
        return json.dumps(data)[:80]

    def _format_bytes(self, n: int) -> str:
        for unit in ("B", "KB", "MB", "GB", "TB"):
            if n < 1024:
                return f"{round(n, 2)} {unit}"
            n /= 1024
        return f"{round(n, 2)} PB"
