"""
Grudarin - Notes Writer
Generates structured reports in Markdown (.md) and JSON formats.
Security findings are highlighted with bold red headers and large fonts.
"""

import json
import os
import time
from datetime import datetime


class NotesWriter:
    """
    Writes session notes, reports, and packet logs to disk.
    Output format is Markdown (.md) for human-readable reports.
    """

    def __init__(self, session_dir):
        self.session_dir = session_dir
        self.report_path = os.path.join(session_dir, "session_report.md")
        self.json_path = os.path.join(session_dir, "session_data.json")
        self.packet_log_path = os.path.join(session_dir, "packets.log")
        self._packet_log_handle = None

    def _open_packet_log(self):
        """Open the packet log file for appending."""
        if self._packet_log_handle is None:
            self._packet_log_handle = open(
                self.packet_log_path, "a", encoding="utf-8"
            )
            self._packet_log_handle.write(
                "TIMESTAMP | PROTOCOL | SRC_MAC | SRC_IP:PORT | "
                "DST_MAC | DST_IP:PORT | LENGTH | FLAGS | INFO\n"
            )
            self._packet_log_handle.write("-" * 140 + "\n")
        return self._packet_log_handle

    def log_packet(self, record):
        """Write a single packet record to the log."""
        try:
            fh = self._open_packet_log()
            ts = datetime.fromtimestamp(record.timestamp).strftime(
                "%H:%M:%S.%f"
            )[:-3]
            src = f"{record.src_ip}:{record.src_port}" if record.src_port else record.src_ip
            dst = f"{record.dst_ip}:{record.dst_port}" if record.dst_port else record.dst_ip
            line = (
                f"{ts} | {record.protocol:<8} | {record.src_mac} | "
                f"{src:<22} | {record.dst_mac} | {dst:<22} | "
                f"{record.length:<7} | {record.flags:<12} | {record.info}\n"
            )
            fh.write(line)
            fh.flush()
        except Exception:
            pass

    def write_final_report(self, network_model, findings=None):
        """Write the complete session report in Markdown and JSON."""
        data = network_model.get_full_data()
        findings_list = findings or []
        self._write_json_report(data, findings_list)
        self._write_markdown_report(data, findings_list)
        if self._packet_log_handle:
            self._packet_log_handle.close()
            self._packet_log_handle = None

    def _write_json_report(self, data, findings):
        """Write full session data as JSON."""
        try:
            data["security_findings"] = findings
            with open(self.json_path, "w", encoding="utf-8") as f:
                json.dump(data, f, indent=2, default=str)
        except Exception as e:
            print(f"  Error writing JSON report: {e}")

    def _write_markdown_report(self, data, findings):
        """Write the full Markdown report."""
        try:
            with open(self.report_path, "w", encoding="utf-8") as f:
                f.write(self._format_markdown(data, findings))
        except Exception as e:
            print(f"  Error writing Markdown report: {e}")

    def _format_markdown(self, data, findings):
        """Format the complete Markdown report."""
        md = []

        # ============================================================
        # HEADER
        # ============================================================
        md.append("# GRUDARIN - Network Monitoring Session Report")
        md.append("")
        md.append(f"> Generated by Grudarin v1.0.0")
        md.append(f"> Report time: `{datetime.now().isoformat()}`")
        md.append("")
        md.append("---")
        md.append("")

        # ============================================================
        # SESSION SUMMARY
        # ============================================================
        session = data["session"]
        md.append("## Session Summary")
        md.append("")
        md.append("| Property | Value |")
        md.append("|----------|-------|")
        md.append(f"| **Start Time** | `{session['start_time']}` |")
        md.append(f"| **End Time** | `{session['end_time']}` |")
        md.append(f"| **Duration** | `{session['duration_seconds']}` seconds |")
        md.append(f"| **Total Packets** | `{session['total_packets']}` |")
        md.append(f"| **Total Data** | `{self._format_bytes(session['total_bytes'])}` |")
        md.append(f"| **Devices Found** | `{len(data['devices'])}` |")
        md.append(f"| **Connections** | `{len(data['connections'])}` |")

        # Count findings by severity
        sev_counts = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
        for f in findings:
            sev = f.get("severity", "info") if isinstance(f, dict) else f.severity
            sev_counts[sev] = sev_counts.get(sev, 0) + 1

        total_vulns = sum(sev_counts.get(s, 0) for s in ["critical", "high", "medium"])
        md.append(f"| **Security Findings** | `{len(findings)}` total, `{total_vulns}` actionable |")
        md.append("")

        # ============================================================
        # PROTOCOL DISTRIBUTION
        # ============================================================
        md.append("## Protocol Distribution")
        md.append("")

        proto_dist = session.get("protocol_distribution", {})
        if proto_dist:
            total = sum(proto_dist.values()) or 1
            sorted_protos = sorted(proto_dist.items(), key=lambda x: x[1], reverse=True)
            md.append("| Protocol | Packets | Percentage |")
            md.append("|----------|---------|------------|")
            for proto, count in sorted_protos:
                pct = count / total * 100
                md.append(f"| {proto} | {count:,} | {pct:.1f}% |")
            md.append("")

        # ============================================================
        # DISCOVERED DEVICES
        # ============================================================
        md.append("## Discovered Devices")
        md.append("")

        devices = data.get("devices", {})
        for idx, (key, dev) in enumerate(devices.items(), 1):
            md.append(f"### Device #{idx}: {dev.get('ip', key)}")
            md.append("")
            md.append("| Property | Value |")
            md.append("|----------|-------|")
            md.append(f"| **MAC Address** | `{dev['mac']}` |")
            md.append(f"| **IP Address** | `{dev['ip']}` |")

            if len(dev.get("all_ips", [])) > 1:
                ips = ", ".join(f"`{ip}`" for ip in dev["all_ips"])
                md.append(f"| **All IPs** | {ips} |")
            if dev.get("hostname"):
                md.append(f"| **Hostname** | `{dev['hostname']}` |")
            if dev.get("vendor"):
                md.append(f"| **Vendor** | {dev['vendor']} |")
            if dev.get("os_hint"):
                md.append(f"| **OS Hint** | {dev['os_hint']} |")
            if dev.get("is_gateway"):
                md.append(f"| **Role** | **Gateway/Router** |")

            md.append(f"| **First Seen** | `{dev['first_seen']}` |")
            md.append(f"| **Last Seen** | `{dev['last_seen']}` |")
            md.append(f"| **Packets Sent** | {dev['packets_sent']:,} |")
            md.append(f"| **Packets Received** | {dev['packets_received']:,} |")
            md.append(
                f"| **Data Sent** | {self._format_bytes(dev['bytes_sent'])} |"
            )
            md.append(
                f"| **Data Received** | {self._format_bytes(dev['bytes_received'])} |"
            )

            if dev.get("protocols"):
                md.append(f"| **Protocols** | {', '.join(dev['protocols'])} |")
            if dev.get("services"):
                md.append(f"| **Services** | {', '.join(dev['services'])} |")
            if dev.get("open_ports"):
                ports_str = ", ".join(str(p) for p in dev["open_ports"][:30])
                md.append(f"| **Open Ports** | `{ports_str}` |")
            if dev.get("ttl_values"):
                md.append(
                    f"| **TTL Values** | {', '.join(str(t) for t in dev['ttl_values'])} |"
                )
            md.append("")

        # ============================================================
        # NETWORK CONNECTIONS
        # ============================================================
        md.append("## Network Connections")
        md.append("")

        connections = data.get("connections", [])
        if connections:
            md.append("| # | Source | Destination | Packets | Data | Protocols |")
            md.append("|---|--------|-------------|---------|------|-----------|")
            for idx, conn in enumerate(connections, 1):
                protos = ", ".join(conn.get("protocols", []))
                md.append(
                    f"| {idx} | `{conn['source']}` | `{conn['destination']}` | "
                    f"{conn['packet_count']:,} | "
                    f"{self._format_bytes(conn['byte_count'])} | {protos} |"
                )
            md.append("")

        # ============================================================
        # DNS HOSTNAME MAPPINGS
        # ============================================================
        dns_cache = data.get("dns_cache", {})
        if dns_cache:
            md.append("## DNS Hostname Mappings")
            md.append("")
            md.append("| IP Address | Hostname |")
            md.append("|------------|----------|")
            for ip, hostname in sorted(dns_cache.items()):
                md.append(f"| `{ip}` | `{hostname}` |")
            md.append("")

        # ============================================================
        # NETWORK CHANGES LOG
        # ============================================================
        changes = data.get("changes_log", [])
        if changes:
            md.append("## Network Changes Log")
            md.append("")
            md.append("| Time | Event | Details |")
            md.append("|------|-------|---------|")
            for change in changes[-100:]:
                event = change.get("event", "unknown")
                ts = change.get("time", "")
                if event == "device_discovered":
                    details = (
                        f"IP=`{change.get('ip', '?')}` "
                        f"MAC=`{change.get('mac', '?')}`"
                    )
                    md.append(f"| `{ts}` | New Device | {details} |")
                elif event == "connection_established":
                    details = (
                        f"`{change.get('source', '?')}` to "
                        f"`{change.get('destination', '?')}` "
                        f"({change.get('protocol', '?')})"
                    )
                    md.append(f"| `{ts}` | New Connection | {details} |")
            md.append("")

        # ============================================================
        # SECURITY FINDINGS - THE BIG RED SECTION
        # ============================================================
        md.append("")
        md.append("---")
        md.append("")
        md.append("---")
        md.append("")

        if findings:
            # Giant red header using HTML in Markdown
            md.append(
                '<h1 style="color: red; font-size: 2.5em; '
                'border: 3px solid red; padding: 15px; text-align: center;">'
                'SECURITY FINDINGS & VULNERABILITIES'
                '</h1>'
            )
            md.append("")
            md.append(
                '<p style="color: red; font-size: 1.3em; font-weight: bold; text-align: center;">'
                f'Total: {len(findings)} findings | '
                f'Critical: {sev_counts.get("critical", 0)} | '
                f'High: {sev_counts.get("high", 0)} | '
                f'Medium: {sev_counts.get("medium", 0)} | '
                f'Low: {sev_counts.get("low", 0)} | '
                f'Info: {sev_counts.get("info", 0)}'
                '</p>'
            )
            md.append("")

            # Severity color mapping for HTML
            severity_styles = {
                "critical": (
                    "color: #ff0000; background-color: #2d0000; "
                    "border-left: 6px solid #ff0000; padding: 12px; "
                    "font-size: 1.2em; font-weight: bold; margin: 10px 0;"
                ),
                "high": (
                    "color: #ff4444; background-color: #1a0000; "
                    "border-left: 6px solid #ff4444; padding: 12px; "
                    "font-size: 1.1em; font-weight: bold; margin: 10px 0;"
                ),
                "medium": (
                    "color: #ff8800; background-color: #1a1100; "
                    "border-left: 5px solid #ff8800; padding: 10px; "
                    "font-size: 1.05em; margin: 8px 0;"
                ),
                "low": (
                    "color: #ddaa00; background-color: #1a1500; "
                    "border-left: 4px solid #ddaa00; padding: 8px; "
                    "margin: 6px 0;"
                ),
                "info": (
                    "color: #88aacc; background-color: #0a1118; "
                    "border-left: 3px solid #88aacc; padding: 8px; "
                    "margin: 6px 0;"
                ),
            }

            severity_labels = {
                "critical": "CRITICAL",
                "high": "HIGH",
                "medium": "MEDIUM",
                "low": "LOW",
                "info": "INFO",
            }

            severity_md_icons = {
                "critical": "**[!!! CRITICAL !!!]**",
                "high": "**[!! HIGH !!]**",
                "medium": "**[! MEDIUM !]**",
                "low": "**[LOW]**",
                "info": "[INFO]",
            }

            # Group by severity
            for sev_level in ["critical", "high", "medium", "low", "info"]:
                sev_findings = [
                    f for f in findings
                    if (f.get("severity") if isinstance(f, dict) else f.severity) == sev_level
                ]
                if not sev_findings:
                    continue

                sev_label = severity_labels[sev_level]
                style = severity_styles[sev_level]

                # Section header
                if sev_level in ("critical", "high"):
                    md.append(
                        f'<h2 style="color: red; font-size: 1.8em; '
                        f'margin-top: 30px;">'
                        f'{sev_label} SEVERITY ({len(sev_findings)} findings)'
                        f'</h2>'
                    )
                elif sev_level == "medium":
                    md.append(
                        f'<h2 style="color: #ff8800; font-size: 1.5em; '
                        f'margin-top: 25px;">'
                        f'{sev_label} SEVERITY ({len(sev_findings)} findings)'
                        f'</h2>'
                    )
                else:
                    md.append(f"### {sev_label} SEVERITY ({len(sev_findings)} findings)")

                md.append("")

                for i, finding in enumerate(sev_findings, 1):
                    if isinstance(finding, dict):
                        title = finding.get("title", "Unknown")
                        desc = finding.get("description", "")
                        affected = finding.get("affected", "")
                        rec = finding.get("recommendation", "")
                        sev = finding.get("severity", "info")
                    else:
                        title = finding.title
                        desc = finding.description
                        affected = finding.affected
                        rec = finding.recommendation
                        sev = finding.severity

                    icon = severity_md_icons.get(sev, "")

                    # HTML block for critical/high with red styling
                    md.append(f'<div style="{style}">')
                    md.append("")
                    md.append(f"{icon} **{title}**")
                    md.append("")
                    md.append(f"{desc}")
                    md.append("")
                    if affected:
                        md.append(f"**Affected:** `{affected}`")
                        md.append("")
                    if rec:
                        if sev in ("critical", "high"):
                            md.append(
                                f'<strong style="color: #ff6666;">'
                                f'Recommendation: {rec}</strong>'
                            )
                        else:
                            md.append(f"**Recommendation:** {rec}")
                        md.append("")
                    md.append("</div>")
                    md.append("")

        else:
            md.append(
                '<h2 style="color: #00cc88; font-size: 1.8em; text-align: center;">'
                'No Security Findings Detected'
                '</h2>'
            )
            md.append("")
            md.append("> No vulnerabilities or misconfigurations were detected during this session.")
            md.append("> This does not guarantee the network is secure - extend scan duration and scope.")
            md.append("")

        # ============================================================
        # FOOTER
        # ============================================================
        md.append("---")
        md.append("")
        md.append(f"*Report generated by Grudarin v1.0.0 at `{datetime.now().isoformat()}`*")
        md.append("")
        md.append("*This tool is for authorized security assessment only.*")
        md.append("")

        return "\n".join(md) + "\n"

    @staticmethod
    def _format_bytes(num_bytes):
        """Format byte count to human-readable string."""
        if num_bytes < 1024:
            return f"{num_bytes} B"
        elif num_bytes < 1024 * 1024:
            return f"{num_bytes / 1024:.1f} KB"
        elif num_bytes < 1024 * 1024 * 1024:
            return f"{num_bytes / (1024 * 1024):.1f} MB"
        else:
            return f"{num_bytes / (1024 * 1024 * 1024):.2f} GB"

    def save_graph_snapshot(self, surface_data, filename):
        """Save a graph snapshot image."""
        try:
            import pygame
            path = os.path.join(self.session_dir, filename)
            pygame.image.save(surface_data, path)
        except Exception as e:
            print(f"  Error saving snapshot: {e}")
